# backend/serverless.yml

custom:
  common: ${file(../config/common.yml)}
  env: ${file(../config/${opt:stage}.yml)}

service: ${self:custom.common.services.baseName}-backend-nodejs-${self:custom.env.stage}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.common.region}
  environment:
    DATABASE_URL: ${ssm:/${self:custom.env.stage}/DATABASE_URL}  # SSMパラメータストアから値を取得

package:
  individually: true
  exclude:
    - layers/**  # レイヤーは含まない
    - node_modules/aws-sdk/**  # 例: aws-sdk モジュールを除外
    - node_modules/.bin/**  # 他に除外したいモジュールを指定
    - node_modules/typescript/**  # 他に除外したいモジュールを指定
    - node_modules/undico-types/**  # 他に除外したいモジュールを指定
    - node_modules/@types/**  # 他に除外したいモジュールを指定

layers:
  myLayer:
    path: layers/layer-nodejs-main
    compatibleRuntimes:
      - nodejs20.x

functions:
  hello:
    handler: src/handler/handler.hello
    layers:
      - { Ref: MyLayerLambdaLayer } # Lambda関数でレイヤーを使用
    events:
      - http:
          path: hello
          method: get



plugins:
  - serverless-offline
