apiVersion: v1
kind: Pod
metadata:
  name: my-server
  labels:  
    app: my-server
spec:
  containers:
    - name: my-server
      image: localhost:5000/my-server:latest
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-server
spec:
  selector:
    app: my-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

