openapi: 3.0.0
info:
  title: Naf_Authentication
  version: 1.0.0-alpha.1
  description: |
    AF Authentication Service.
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.255 V1.0.0; 5G System;Uncrewed Aerial System Service Supplier (USS) Services; Stage 3
  url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.255/

servers:
  - url: '{apiRoot}/naf-auth/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501

security:
  - {}
  - oAuth2ClientCredentials:
    - naf-auth

paths:
  /request-auth:
    post:
      summary: UAV authentication
      tags:
        - UAV authentication
      requestBody:
        description: UAV authentication
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UAVAuthInfo'
      responses:
        '200':
          description: UAV Auth response or message exchange
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UAVAuthResponse'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          description: The request is rejected by the USS and more details (not only the ProblemDetails) are returned.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetailsAuthenticateAuthorize'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
      callbacks:
        reauthRevokeNotification:
          '{request.body#/notifyUri}':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ReauthRevokeNotify'
              responses:
                '204':
                  description: Successful Notification response
                '307':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/400'
                '401':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29571_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            naf-auth: Access to the Naf_auth API





  schemas:
#
# STRUCTURED DATA TYPES
#
    UAVAuthInfo:
      description: UAV auth data
      type: object
      required:
        - gpsi
        - serviceLevelId
      properties:
        gpsi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        serviceLevelId:
          type: string
        notifyUri:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
        ipAddr:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/IpAddr'
        pei:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Pei'
        authMsg:
          type: string
        uavLocInfo:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/UserLocation'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'

    UAVAuthResponse:
      description: UAV auth response data
      type: object
      required:
        - gpsi
      properties:
        gpsi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        serviceLevelId:
          type: string
        authSesCorId:
          type: string
        authMsg:
          type: string
        authResult:
          $ref: '#/components/schemas/AuthResult'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'


    ReauthRevokeNotify:
      description: UAV related notification
      type: object
      required:
        - gpsi
        - serviceLevelId
        - notifyType
      properties:
        gpsi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        serviceLevelId:
          type: string
        authSesCorId:
          type: string
        authMsg:
          type: string
        notifyType:
          $ref: '#/components/schemas/NotifyType'
        revokeCause:
          $ref: '#/components/schemas/RevokeCause'
        ipAddr:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/IpAddr'


#
# SIMPLE DATA TYPES
#

#
# ENUMERATIONS
#

    AuthResult:
      anyOf:
        - type: string
          enum:
          - AUTH_SUCCESS
        - type: string
    NotifyType:
      anyOf:
        - type: string
          enum:
          - REAUTHENTICATE
          - REAUTHORIZE
          - REVOKE
        - type: string
    RevokeCause:
      anyOf:
        - type: string
          enum:
          - UNSPECIFIED

    ProblemDetailsAuthenticateAuthorize:
      description: Extends ProblemDetails to indicate more details during Authentication failure
      allOf:
        - $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        - $ref: '#/components/schemas/AdditionInfoAuthenticateAuthorize'
    AdditionInfoAuthenticateAuthorize:
      description: Indicates additional information during authentication failure
      type: object
      properties:
        uasResRelInd:
          type: boolean
          description: Indicates to release the UAV resources during authentication failure, when set to "true". Default is set to "false".
