# config/common.yml

# リージョン設定
region: ap-northeast-1

baseName: test-signed-20250923-12

# ステージごとのサフィックス定義
# stages:
#   dev:
#     suffix: dev
#   prod:
#     suffix: prod

backend-js:
  runtime: nodejs20.x

# 共通デプロイバケット 事前に作成すること
deploymentBucket:
  name: deployment-serverless-123-${opt:stage}
  maxPreviousDeploymentArtifacts: 1 # デプロイ用S3バケットには最大世代

# プロジェクト名とオーナーの定義
projectName: my-awesome-project
owner: your-name
