openapi: 3.0.0

info:
  title: Nnef_Authentication
  version: 1.0.0-alpha.1
  description: |
    NEF Auth Service.
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.256 V1.0.0; 5G System;Uncrewed Aerial Systems Network Function (UAS-NF);Aerial Management Services; Stage 3
  url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.256/

servers:
  - url: '{apiRoot}/nnef-authentication/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501

security:
  - {}
  - oAuth2ClientCredentials:
    - nnef-authentication

paths:
  /uav-authentications:
    post:
      summary:  UAV authentication
      tags:
        - UAV authentication
      requestBody:
        description: UAV authentication
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UAVAuthInfo'
      responses:
        '200':
          description: UAV Auth response or message exchange
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UAVAuthResponse'
        '307':
          $ref: 'TS29571_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29571_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '504':
          $ref: 'TS29571_CommonData.yaml#/components/responses/504'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
      callbacks:
        authNotification:
          '{request.body#/authNotification }':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/AuthNotification'
              responses:
                '204':
                  description: Successful Notification response
                '307':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/400'
                default:
                  $ref: 'TS29571_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nnef-authentication: Access to the Nnef_authentication API





  schemas:
#
# STRUCTURED DATA TYPES
#
    UAVAuthInfo:
      description: UAV auth data
      type: object
      required:
        - gpsi
        - serviceLevelId
        - nfType
      properties:
        gpsi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        serviceLevelId:
          type: string
        authNotificationURI:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
        ipAddr:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/IpAddr'
        pei:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Pei'
        authServerAddress:
          type: string
        authMsg:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/RefToBinaryData'
        ueLocInfo:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/UserLocation'
        dnn:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
        sNssai:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/ExtSnssai'
        nfType:
          $ref: 'TS29510_Nnrf_NFManagement.yaml#/components/schemas/NFType'

    UAVAuthResponse:
      description: UAV auth response data
      type: object
      required:
        - gpsi
      properties:
        gpsi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        serviceLevelId:
          type: string
        authSessCorrId:
          type: string
        authMsg:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/RefToBinaryData'
        authResult:
          $ref: '#/components/schemas/AuthResult'
        uasResourceRelease:
          type: boolean
          default: false

    AuthNotification:
      description: UAV related notification
      type: object
      required:
        - gpsi
        - serviceLevelId
        - notifType
      properties:
        gpsi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        serviceLevelId:
          type: string
        authSessCorrId:
          type: string
        authMsg:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/RefToBinaryData'
        notifType:
          $ref: '#/components/schemas/NotifType'
        revokeCause:
          type: string
        ipAddr:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/IpAddr'

    UAVAuthFailure:
      description: UAV auth failure
      type: object
      required:
        - error
      properties:
        error:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        uasResourceRelease:
          type: boolean

#
# SIMPLE DATA TYPES
#

#
# ENUMERATIONS
#

    AuthResult:
      description: Enumeration representing the result of authentication and/or authorization.
      anyOf:
        - type: string
          enum:
          - AUTH_SUCCESS
        - type: string
    NotifType:
      description: Enumeration representing the type of notification.
      anyOf:
        - type: string
          enum:
          - REAUTH
          - UPDATEAUTH
          - REVOKE
        - type: string
