
service: csv-processing-lambdas

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  memorySize: 256
  timeout: 30
  environment:
    BUCKET_NAME: your-s3-bucket-name
    STATE_MACHINE_ARN: ${param:stateMachineArn}

functions:
  triggerLambda:
    handler: triggerLambda.handler
    events:
      - http:
          path: trigger
          method: post

  csvEntryLambda:
    handler: csvEntryLambda.handler

  processCsvLambda:
    handler: processCsvLambda.handler

  aggregationLambda:
    handler: aggregationLambda.handler

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
