custom:
  common: ${file(../../config/common.yml)}
  env: ${file(../../config/${opt:stage}.yml)}
  rdsMasterUserPassword: password123
service: ${self:custom.common.services.baseName}-rds

provider:
  name: aws
  region: ${self:custom.common.region}

resources:
  Resources:
    # RDSインスタンスの作成
    PostgresRdsInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceClass: db.t4g.micro  # 無料枠に対応
        Engine: postgres
        DBInstanceIdentifier: ${self:custom.env.stage}-rds-instance
        AllocatedStorage: 20           # 無料枠に対応
        StorageType: gp2
        MasterUsername: postgresman
        MasterUserPassword: ${self:custom.rdsMasterUserPassword}
        DBName: mydatabase
        BackupRetentionPeriod: 7
        MultiAZ: false                  # コスト削減のためにMulti-AZを無効化
        PubliclyAccessible: false       # セキュリティ強化
        VPCSecurityGroups:
          - Fn::ImportValue: RdsSgId # ネットワークリソースからRDS用セキュリティグループをインポート
        DBSubnetGroupName: !Ref RdsSubnetGroup
        Tags:
          - Key: Name
            Value: ${self:custom.env.stage}-rds-instance
          - Key: Environment
            Value: ${self:custom.env.stage}
          - Key: Project
            Value: ${self:custom.common.projectName}
          - Key: Owner
            Value: ${self:custom.common.owner}

    # RDSサブネットグループの作成
    RdsSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: "RDS Subnet Group"
        SubnetIds:
          - Fn::ImportValue: PrivateSubnetAId # 1つ目のサブネット (ap-northeast-1a)
          - Fn::ImportValue: PrivateSubnetBId # 2つ目のサブネット (ap-northeast-1c)
        Tags:
          - Key: Name
            Value: ${self:custom.env.stage}-rds-subnet-group
          - Key: Environment
            Value: ${self:custom.env.stage}
          - Key: Project
            Value: ${self:custom.common.projectName}
          - Key: Owner
            Value: ${self:custom.common.owner}


  Outputs:
    # RDSインスタンスIDの出力
    RdsInstanceIdOutput:
      Description: "RDS instance identifier"
      Value:
        Ref: PostgresRdsInstance
      Export:
        Name: ${self:custom.env.stage}-rds-instance-id
    # RDSエンドポイントの出力
    RdsEndpointAddress:
      Description: "The connection endpoint for the RDS DB instance"
      Value: !GetAtt PostgresRdsInstance.Endpoint.Address
      Export:
        Name: ${self:custom.env.stage}-rds-endpoint
    # RDSポートの出力
    RdsEndpointPort:
      Description: "The port for the RDS DB instance"
      Value: !GetAtt PostgresRdsInstance.Endpoint.Port
      Export:
        Name: ${self:custom.env.stage}-rds-port
    # RDSユーザー名の出力
    RdsMasterUsername:
      Description: "The master username for the RDS DB instance"
      Value: !GetAtt PostgresRdsInstance.MasterUsername
      Export:
        Name: ${self:custom.env.stage}-rds-master-username
    # RDSパスワードの出力
    RdsMasterUserPassword:
      Description: "The master user password for the RDS DB instance"
      Value: ${self:custom.rdsMasterUserPassword}
      Export:
        Name: ${self:custom.env.stage}-rds-master-user-password
    # RDSパスワードの出力
    DBName:
      Description: "The master user password for the RDS DB instance"
      Value: !GetAtt PostgresRdsInstance.DBName
      Export:
        Name: ${self:custom.env.stage}-rds-dbname
